# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:

  - package-ecosystem: maven
    directory: "/symja_android_library"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups: 
       dev-dependencies: 
          patterns:
            - "*jackson*" # jsckson fasterxml
            - "*hipparchus*"  # hipparchus.org
            - "*undertow*"  # undertow.io
            - "*fastutil*"  # unimi.it
            - "*biojava*"  # biojava.org
            - "*log4j*"  # log4j.org
            - "*junit*"  # junit.org
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"