tasks:
  - init: mvn -f symja_android_library/pom.xml clean install -DskipTests
    command: mvn -f symja_android_library/pom.xml exec:java -pl matheclipse-core -Dexec.mainClass="org.matheclipse.core.eval.Console"
